version: '3.8'

services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 322489
      MYSQL_DATABASE: cadastro

    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cadastro
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 322489
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    restart: on-failure

volumes:
  mysql-data:
